// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "no light freddy 1":return img`
......ffff......
.eee..ffff..eee.
.ede..cccc..ede.
.eeb.ffffff.bee.
....eeeeeeee....
...eeeeeeeeee...
...effeeeeffe...
..eef1eeee1fee..
..eeeeeeeeeeee..
...eeeeffeeee...
...1c1bbbb1c1...
....eeeeeeee....
.....eeeeee.....
.......bb.......
..ee.efeefe.ee..
.ebeeeffffeeebe.
eeeeeefddfeeeeee
eeceeeddddeeecee
eeceeddddddeecee
eeceeddddddeecee
bbbeeeddddeeebbb
eee.eeeddeee.eee
eee..eeeeee..eee
eee.e..bb..e.eee
eee.eeeeeeee.eee
.b..beeeeeeb..b.
ee..bbeeeebb..ee
eee.eb....be.eee
eeeecee..eeceeee
eefecee..eeceeee
.fffcee..eec..e.
..f.eee..eee....
....eee..eee....
.....b....b.....
....eee..eee....
....eee..eee....
....eee..eee....
....eee..eee....
....eee..eee....
.....b....b.....
....eee..eee....
..eeeee..eeeee..
.eeeeee..eeeeee.
`;
            case "image4":
            case "freddy 2":return img`
......ffff......
.eee..ffff..eee.
.eee..cccc..eee.
.eeb.ffffff.bee.
....eeeeeeee....
...eeeeeeeeee...
...eeeeeeeeee...
..eeeeeeeeeeee..
..eeeeeeeeeeee..
...eeeeeeeeee...
...eeeeeeeeee...
....eeeeeeee....
.....eeeeee.....
.......bb.......
..ee.eeeeee.ee..
.ebeeeeeeeeeebe.
eeeeeeeeeeeeeeee
eeceeeeeeeeeecee
eeceeeeeeeeeecee
eeceeeeeeeeeecee
bbbeeeeeeeeeebbb
eee.eeeeeeee.eee
eee..eeeeee..eee
eee.e..bb..e.eee
eee.eeeeeeee.eee
.b..beeeeeeb..b.
ee..bbeeeebb..ee
eee.eb....be.eee
eeeecee..eeceeee
eeeecee..eecefee
.e..cee..eeeffe.
....eee..eeef...
....eee...b.....
.....b...eee....
....eee..eee....
....eee..eee....
....eee..eee....
....eee..eee....
....eee...b.....
.....b...eee....
....eee..eeeee..
..eeeee..eeeeee.
.eeeeee.........
`;
            case "image6":
            case "bonnie 1":return img`
.............aaa
............aaaa
.aaa........aaa.
aaaaa......aaa..
accaaaaaaaaaa...
ac.aaaaaaaaaa...
ac.aaaaaaaaaa...
..aaaaaaaaaaaa..
..aaaaaaaaaaaa..
...aaaaaaaaaa...
...aaaaaaaaaa...
....aaaaaaaa....
.....aaaaaa.....
.......bb.......
..aa.aaaaaa.aa..
.abaaaaaaaaaaba.
aaaaaaaaaaaaaaaa
aacaaaaaaaaaacaa
aacaaaaaaaaaacaa
aacaaaaaaaaaacaa
bbbaaaaaaaaaabbb
aaa.aaaaaaaa.aaa
aaa..aaaaaa..aaa
aaa.a..bb..a.aaa
aaa.aaa11aaa.aaa
.b..baa11aab..b.
aa..bbaaaabb..aa
aaa.ab....ba.aaa
aaaacaa..aacaaaa
aaaacaa..aaca.aa
.a..caa..aac..a.
....aaa..aaa....
....aaa..aaa....
.....b....b.....
....aaa..aaa....
....aaa..aaa....
....aaa..aaa....
....aaa..aaa....
....aaa..aaa....
.....b....b.....
....aaa..aaa....
..aaaaa..aaaaa..
.aaaaaa..aaaaaa.
`;
            case "image8":
            case "freddy 5":return img`
......ffff......
.eee..ffff..eee.
.eee..cccc..eee.
.eeb.ffffff.bee.
....eeeeeeee....
...eeeeeeeeee...
...eeeeeeeeee...
..eeeeeeeeeeee..
..eeeeeeeeeeee..
...eeeeeeeeee...
...eeeeeeeeee...
....eeeeeeee....
.....eeeeee.....
.......bb.......
..ee.eeeeee.ee..
.ebeeeeeeeeeebe.
eeeeeeeeeeeeeeee
eeceeeeeeeeeecee
eeceeeeeeeeeecee
eeceeeeeeeeeecee
bbbeeeeeeeeeebbb
eee.eeeeeeee.eee
eee..eeeeee..eee
eee.e..bb..e.eee
eee.eeeeeeee.eee
.b..beeeeeeb..b.
ee..bbeeeebb..ee
eee.eb....be.eee
eeeecee..eeceeee
eeeecee..eecefee
.e..eee..eecffe.
....eee..eeef...
.....b...eee....
....eee...b.....
....eee..eee....
....eee..eee....
....eee..eee....
....eee..eee....
.....b...eee....
....eee...b.....
..eeeee..eee....
.eeeeee..eeeee..
.........eeeeee.
`;
            case "image9":
            case "bonnie back walk cycle 1":return img`
.............aaa
............aaaa
.aaa........aaa.
aaaaa......aaa..
accaaaaaaaaaa...
ac.aaaaaaaaaa...
ac.aaaaaaaaaa...
..aaaaaaaaaaaa..
..aaaaaaaaaaaa..
...aaaaaaaaaa...
...aaaaaaaaaa...
....aaaaaaaa....
.....aaaaaa.....
.......bb.......
..aa.aaaaaa.aa..
.abaaaaaaaaaaba.
aaaaaaaaaaaaaaaa
aacaaaaaaaaaacaa
aacaaaaaaaaaacaa
aacaaaaaaaaaacaa
bbbaaaaaaaaaabbb
aaa.aaaaaaaa.aaa
aaa..aaaaaa..aaa
aaa.a..bb..a.aaa
aaa.aaa11aaa.aaa
.b..baa11aab..b.
aa..bbaaaabb..aa
aaa.ab....ba.aaa
aaaacaa..aacaaaa
aaaacaa..aaca.aa
.a..aaa..aac..a.
....aaa..aaa....
.....b...aaa....
....aaa...b.....
....aaa..aaa....
....aaa..aaa....
....aaa..aaa....
....aaa..aaa....
.....b...aaa....
....aaa...b.....
..aaaaa..aaa....
.aaaaaa..aaaaa..
.........aaaaaa.
`;
            case "image10":
            case "bonnie walk 2":return img`
.............aaa
............aaaa
.aaa........aaa.
aaaaa......aaa..
accaaaaaaaaaa...
ac.aaaaaaaaaa...
ac.aaaaaaaaaa...
..aaaaaaaaaaaa..
..aaaaaaaaaaaa..
...aaaaaaaaaa...
...aaaaaaaaaa...
....aaaaaaaa....
.....aaaaaa.....
.......bb.......
..aa.aaaaaa.aa..
.abaaaaaaaaaaba.
aaaaaaaaaaaaaaaa
aacaaaaaaaaaacaa
aacaaaaaaaaaacaa
aacaaaaaaaaaacaa
bbbaaaaaaaaaabbb
aaa.aaaaaaaa.aaa
aaa..aaaaaa..aaa
aaa.a..bb..a.aaa
aaa.aaa11aaa.aaa
.b..baa11aab..b.
aa..bbaaaabb..aa
aaa.ab....ba.aaa
aaaacaa..aacaaaa
aaaacaa..aaca.aa
.a..caa..aaa..a.
....aaa..aaa....
....aaa...b.....
.....b...aaa....
....aaa..aaa....
....aaa..aaa....
....aaa..aaa....
....aaa..aaa....
....aaa...b.....
.....b...aaa....
....aaa..aaaaa..
..aaaaa..aaaaaa.
.aaaaaa.........
`;
            case "image3":
            case "freddy 1":return img`
......ffff......
.eee..ffff..eee.
.ede..cccc..ede.
.eeb.ffffff.bee.
....eeeeeeee....
...effeeeeffe...
...e11eeee11e...
..ee18eeee81ee..
..eeeeeeeeeeee..
...eeeeffeeee...
...1c1bbbb1c1...
....eeeeeeee....
.....eeeeee.....
.......bb.......
..ee.efeefe.ee..
.ebeeeffffeeebe.
eeeeeefddfeeeeee
eeceeeddddeeecee
eeceeddddddeecee
eeceeddddddeecee
bbbeeeddddeeebbb
eee.eeeddeee.eee
eee..eeeeee..eee
eee.e..bb..e.eee
eee.eeeeeeee.eee
.b..beeeeeeb..b.
ee..bbeeeebb..ee
eee.eb....be.eee
eeeecee..eeceeee
eefecee..eeceeee
.fffcee..eec..e.
..f.eee..eee....
....eee..eee....
.....b....b.....
....eee..eee....
....eee..eee....
....eee..eee....
....eee..eee....
....eee..eee....
.....b....b.....
....eee..eee....
..eeeee..eeeee..
.eeeeee..eeeeee.
`;
            case "image14":
            case "freddy side 0":return img`
................
......ffff......
......feef......
......ceec......
.....ffbbff.....
....eeeeeeee....
...eeeeeeeffe...
...eeeeeee11e...
...eeeeeee18e...
...eeeeeeeeee...
...eeeeeeeeeff..
...eeeeeee1c1...
....eeeeeeee....
.....eeeeee.....
.......bb.......
.....ecccef.....
....eceeecef....
...eeecccefed...
...eeececeedd...
...eeececeedd...
...eeececeedd...
...eeebbbeeed...
....eececeee....
.....ececee.....
....e.cecb.e....
....eececeee....
.....ebbbee.....
.....ccecec.....
.....ceeece.....
.....ceeeec.....
.....ceefec.....
.....ccfffc.....
.......bf.......
.....eeeee......
.....eeeee......
.....eeeee......
.....eeeee......
.....eeeee......
......eee.......
......bb........
.....ebbe.......
.....eeeee......
.....eeeeee.....
......eeeeee....
................
`;
            case "image15":
            case "Golden Freddy 1":return img`
......ffff......
.555..ffff..555.
.5d5..aaaa..5d5.
.55b.ffffff.b55.
....55555555....
...5555555555...
...5ff5555ff5...
..55f155551f55..
..555555555555..
...5555ff5555...
...1c1bbbb1c1...
....55555555....
.....555555.....
.......bb.......
..55.5a55a5.55..
.5b555aaaa555b5.
555555adda555555
554555dddd555455
55455dddddd55455
55455dddddd55455
bbb555dddd555bbb
555.555dd555.555
555..555555..555
555.5..bb..5.555
555.55555555.555
.b..b555555b..b.
55..bb5555bb..55
555.5b....b5.555
5555455..5545555
55f5455..5545555
.fff455..554..5.
..f.555..555....
....555..555....
.....b....b.....
....555..555....
....555..555....
....555..555....
....555..555....
....555..555....
.....b....b.....
....555..555....
..55555..55555..
.555555..555555.
`;
            case "image13":
            case "puppet":return img`
................
................
................
................
......1111......
.....111111.....
....11111111....
....1ff11ff1....
....11a11a11....
....22a11a22....
....22a11a22....
.....1ffff1.....
......1ff1......
.......22.......
.......ff.......
.......ff.......
......ff1f......
....fff1ffff....
...f.fff1ff.f...
...f.ff1fff.f...
...f..ffff..f...
..f....ff....f..
..1....ff....1..
..f....ff....f..
..1....ff....1..
..f...ffff...f..
..1...ffff...1..
.fff..ffff..fff.
f.f.f.f..f.f.f.f
..f...f..f...f..
......f..f......
.....f....f.....
.....f....f.....
.....1....1.....
.....f....f.....
....1......1....
....f......f....
....1......1....
....f......f....
....1......1....
....f......f....
....1......1....
....f......f....
....f......f....
................
`;
            case "image16":
            case "Chica":return img`
................
................
.....5.55.5.....
......5555......
....55555555....
...5555555555...
...5115555115...
..551755557155..
..555555555555..
...5555445555...
...5554444555...
....55544555....
.....555555.....
.......bb.......
..55.131131.55..
.5b5513131155b5.
5555511113155555
5545551331555455
5545555115555455
5545555555555455
bbb5555555555bbb
555.55555555.555
555..555555..555
555.5..bb..5.555
555.55555555.555
.b..b555555b..b.
55..bb5555bb..55
555.5b....b5.555
5555455..5545555
55.5455..5545555
....455..554..5.
....555..555....
....555..555....
.....b....b.....
....444..444....
....444..444....
....444..444....
....444..444....
....444..444....
.....b....b.....
....444..444....
..44444..44444..
.444444..444444.
`;
            case "image18":
            case "Foxy":return img`
222..........222
2ee2...2....2ee2
2ee2..2.2.2.2ee2
.22b...222..b22.
....2222ff22....
...fee2f22ee2...
...ffff222112...
..22ff22225122..
.222223ff322222.
.22223333332222.
...1c1b15b1c1...
....22222222....
.....222222.....
.......bb.......
..22.2dddd2.22..
.2b22dddddd22b2.
22222ddbddd222f2
2bc.2dfbbdd2.cbf
fbc.2dfbbfd2.cfb
2fc.2dfbbfd2.c22
bbb.2ddbfdd2.bbb
222.22dddd22.222
222..222222..222
222.e..bb..e.222
222.eeeeeeee.222
ccc.beeeeeeb..b.
bbb.bbeeeebb..bb
.b..eb....be.bbb
b...eee..eeebbbb
b.b.eee..effbcbb
.b..bfe..ebf..b.
....fbe..efe....
....eee..eee....
.....b....b.....
.....f....f.....
.....b....b.....
.....b....b.....
.....f....f.....
.....b....b.....
.....b....b.....
....bbb..bbb....
..cbbcb..bcbbc..
.cbbbcb..bcbbbc.
`;
            case "image11":
            case "Spring Trap":return img`
.............7..
...7........777.
..77.......77777
..767.....776677
..7677777776..77
...7777777777..7
...7667227667...
..77f177271f77..
..777f7777f777..
...7777ff7777...
...1c666666c1...
....76611667....
.....277777.....
......2222......
..66.667266.66..
.6b6666666666b6.
6666667777666666
62c6677777266c66
26c6677777726c66
62c6677777266c66
bbb6667777666bbb
777.66666666.777
777..666666..777
777.72222227.777
777.77777777.777
.b..b777777b..b.
77..bb7777bb..77
727.ab....ba.77b
7b2bc77..77c2bb7
bb.bc77..77c2.bb
.b..c77..77c..2.
....777..777....
....777..777....
.....b....b.....
....666..662....
....666..626....
....666..666....
....666..666....
....666..666....
.....b....b.....
....bbb..bbb....
..22bbb..bbb22..
.bbbbb2..2bbbbb.
`;
            case "image17":
            case "Endo":return img`
................
................
................
................
................
.....bbbbbb.....
.....11bb11.....
.....18bb81.....
.....bbbbbb.....
.....bbccbb.....
.....bb11bb.....
.....bbbbbb.....
.......bb.......
.......bb.......
ff.....bb.....ff
ffbbbbbbbbbbbbff
ff..2..bb..2..ff
b...2.bbbb.2...b
b....2.bb.2....b
b....2bbbb2....b
b.....2bb2.....b
b......bb......b
ff.....bb.....ff
b......bb......b
b......bb......b
ff..bbbbbbbb..ff
bb..bbbbbbbb..bb
bbb..b.bb.b..bbb
bbbb.b....b.bbbb
bbcb.b....b.bcbb
.b...b....b...b.
.....b....b.....
....ff....ff....
.....b....b.....
.....f....f.....
.....b....b.....
.....b....b.....
.....f....f.....
.....b....b.....
.....b....b.....
....bbb..bbb....
..cbbcb..bcbbc..
.cbbbcb..bcbbbc.
`;
            case "image12":
            case "freddy side 1":return img`
................
................
......ffff......
......feef......
......ceec......
.....ffbbff.....
....eeeeeeee....
...eeeeeeeffe...
...eeeeeee11e...
...eeeeeee18e...
...eeeeeeeeee...
...eeeeeeeeeff..
...eeeeeee1c1...
....eeeeeeee....
.....eeeeee.....
.......bb.......
.....ecccef.....
....eceeecef....
...eeecccefed...
...eeececeedd...
...eeececeedd...
...eeececeedd...
...eeebbbeeed...
....eececeee....
.....ececee.....
....e.cecb.e....
....eececeee....
.....ebbbee.....
.....ccecec.....
.....ceeece.....
.....ceeeec.....
.....cecfcc.....
.....ccfffc.....
.......bf.......
.....eeeee......
.....eeeee......
.....eeeee......
.....eeeee......
.....eeeee......
.....eeeee......
......eee.......
......bb........
.....ebbe.......
.....eeeee......
.....eeeeee.....
`;
            case "image19":
            case "freddy side 2":return img`
................
................
......ffff......
......feef......
......ceec......
.....ffbbff.....
....eeeeeeee....
...effeeeeeee...
...e11eeeeeee...
...e81eeeeeee...
...eeeeeeeeee...
..ffeeeeeeeee...
...1c1eeeeeee...
....eeeeeeee....
.....eeeeee.....
.......bb.......
.....feccce.....
....feceeece....
...defeccceee...
...ddeececeee...
...ddeececeee...
...ddeececeee...
...deeebbbeee...
....eeececee....
.....eecece.....
....e.bcec.e....
....eeececee....
.....eebbbe.....
.....eecece.....
.....eceeec.....
.....ceeeec.....
.....ecccec.....
.....eeeece.....
........b.......
......eeeee.....
......eeeee.....
......eeeee.....
......eeeee.....
......eeeee.....
......eeeee.....
.......eee......
........bb......
.......ebbe.....
......eeeee.....
.....eeeeee.....
`;
            case "image20":
            case "freddy side 3":return img`
................
................
......ffff......
......feef......
......ceec......
.....ffbbff.....
....eeeeeeee....
...effeeeeeee...
...e11eeeeeee...
...e81eeeeeee...
...eeeeeeeeee...
..ffeeeeeeeee...
...1c1eeeeeee...
....eeeeeeee....
.....eeeeee.....
.......bb.......
.....feccce.....
....feceeece....
...defeccceee...
...ddeececeee...
...ddeececeee...
...ddeececeee...
...deeebbbeee...
....eeececee....
.....eecece.....
....e.bcec.e....
....eeececee....
.....eebbbe.....
.....eecece.....
.....eceeec.....
.....ceeeec.....
.....ecccec.....
.....eeeece.....
........b.......
......eeeee.....
......eeeee.....
......eeeee.....
......eeeee.....
......eeeee.....
.......eee......
........bb......
.......ebbe.....
......eeeee.....
.....eeeeee.....
....eeeeee......
`;
            case "image5":
            case "freddy 3":return img`
......ffff......
.eee..ffff..eee.
.ede..cccc..ede.
.eeb.ffffff.bee.
....eeeeeeee....
...effeeeeffe...
...e11eeee11e...
..ee18eeee81ee..
..eeeeeeeeeeee..
...eeeeffeeee...
...1c1bbbb1c1...
....eeeeeeee....
.....eeeeee.....
.......bb.......
..ee.efeefe.ee..
.ebeeeffffeeebe.
eeeeeefddfeeeeee
eeceeeddddeeecee
eeceeddddddeecee
eeceeddddddeecee
bbbeeeddddeeebbb
eee.eeeddeee.eee
eee..eeeeee..eee
eee.e..bb..e.eee
eee.eeeeeeee.eee
.b..beeeeeeb..b.
ee..bbeeeebb..ee
eee.eb....be.eee
eeeecee..eeceeee
eefecee..eeceeee
.fffeee..eec..e.
..f.eee..eee....
.....b...eee....
....eee...b.....
....eee..eee....
....eee..eee....
....eee..eee....
....eee..eee....
.....b...eee....
....eee...b.....
..eeeee..eee....
.eeeeee..eeeee..
.........eeeeee.
`;
            case "image2":
            case "freddy 0":return img`
......ffff......
.eee..ffff..eee.
.ede..cccc..ede.
.eeb.ffffff.bee.
....eeeeeeee....
...effeeeeffe...
...e11eeee11e...
..ee18eeee81ee..
..eeeeeeeeeeee..
...eeeeffeeee...
...1c1bbbb1c1...
....eeeeeeee....
.....eeeeee.....
.......bb.......
..ee.efeefe.ee..
.ebeeeffffeeebe.
eeeeeefddfeeeeee
eeceeeddddeeecee
eeceeddddddeecee
eeceeddddddeecee
bbbeeeddddeeebbb
eee.eeeddeee.eee
eee..eeeeee..eee
eee.e..bb..e.eee
eee.eeeeeeee.eee
.b..beeeeeeb..b.
ee..bbeeeebb..ee
eee.eb....be.eee
eeeecee..eeceeee
eefecee..eeceeee
.fffcee..eee..e.
..f.eee..eee....
....eee...b.....
.....b...eee....
....eee..eee....
....eee..eee....
....eee..eee....
....eee..eee....
....eee...b.....
.....b...eee....
....eee..eeeee..
..eeeee..eeeeee.
.eeeeee.........
`;
            case "image7":
            case "Bonnie 1":return img`
.aa..........a..
aaaa........aaa.
aaaa.......aaaaa
aaaca.....aaccaa
aaacaaaaaaac..aa
aa.aaaaaaaaaa..a
...a11aaaa11a...
..aa13aaaa31aa..
..aaaaaaaaaaaa..
...aaaaffaaaa...
...1cbbbbbbc1...
....abbaabba....
.....aaaaaa.....
.......bb.......
..aa.a2aa2a.aa..
.abaaa2222aaaba.
aaaaaa2bb2aaaaaa
aacaabbbbbbaacaa
aacaabbbbbbaacaa
aacaabbbbbbaacaa
bbbaaabbbbaaabbb
aaa.aaabbaaa.aaa
aaa..aaaaaa..aaa
aaa.a..bb..a.aaa
aaa.aaaaaaaa.aaa
.b..baaaaaab..b.
aa..bbaaaabb..aa
aaa.ab....ba.aaa
aaaacaa..aacaaaa
aa.acaa..aaca.aa
.a..caa..aac..a.
....aaa..aaa....
....aaa..aaa....
.....b....b.....
....aaa..aaa....
....aaa..aaa....
....aaa..aaa....
....aaa..aaa....
....aaa..aaa....
.....b....b.....
....aaa..aaa....
..aaaaa..aaaaa..
.aaaaaa..aaaaaa.
`;
            case "image21":
            case "Withered Freddy":return img`
......ffff......
.eee..ffff..eee.
.e4e..cccc..e4e.
.eeb.ffffff.bee.
....eeeeeeee....
...effeeeeffe...
...e11eeee11e...
..ee18eeee81ee..
..eeeeeeeeeeee..
...eee4ff4eee...
...1c444444c1...
....ee4ee4ee....
.....eeeeee.....
.......bb.......
..ee.efeefe.ee..
.ebeeeffffeeebe.
eeeeeef44feeeeee
eeceee4444eeecee
eecee444444eece.
eecee444444eecee
bbbeee4444eeebbb
eee.eee44eee.eee
eee..eeeeee..eee
.ee.e..bb..e.eee
eee.eeeeeeee.eee
.b..beeeeeeb..b.
ee..bbeeeebb..ee
eee.eb....be.eee
eeeecee..eeceeee
eefecee..eeceeee
.fffcee..eec..e.
..f.eee..eee....
....eee..eee....
.....b....b.....
....eee..eee....
....eee..eee....
....eee..eee....
....eee..eee....
....eee..eee....
.....b....b.....
....eee..eee....
..eeeee..eeeee..
.eeeeee..eeeeee.
`;
            case "image22":
            case "Withered Chica":return img`
........................................
........................................
.................5.55.5.................
..................5555..................
................55555555................
...............5555555555...............
...............5115555115...............
..............551755557155..............
..............555555555555..............
...............5555445555...............
................b..bb..b................
................55544555................
.................555555.................
...................bb...................
......5555b5555..131131..5555b5555......
....2b5555b555555131311555555b5555b2....
...2b.5555b4445b51111315b5444b5555.b2...
..2bb.....55555555133155555555.....bb2..
..2b22..........55511555..........22b2..
..2bbb..........55555555..........bbb2..
..22b2..........55555555..........2b22..
...b.2..........55555555..........2.b...
.................555555.................
................5..bb..5................
................55555555................
................b555555b................
................bb5555bb................
................5b....b5................
................555..555................
................555..555................
................555..555................
................555..555................
................555..555................
.................b....b.................
................444..444................
................444..444................
................444..444................
................444..444................
................444..444................
.................b....b.................
................444..444................
..............44444..44444..............
.............444444..444444.............
`;
            case "image23":
            case "Withered Bonnie":return img`
.aa..........a..
aaaa........aaa.
aaaa.......aaaaa
aaaca.....aaccaa
aaacaacaacac..aa
aa.acccccccca..a
...affccccffa...
..aaf2cccc2faa..
..acccccccccca..
...acccccccca...
...1cccccccc1...
....a11cc11a....
.....aaaaaa.....
.......bb.......
..aa.a2aa2a.a...
.abaaa2222aaa2..
aaaaaa2bb2aaa2..
aacaabbbbbbaab2.
aacaabbbbbbaab2.
aacaabbbbbbaab22
bbbaaabbbbaaabbb
aaa.aaabbaaa.2b2
aaa..aaaaaa..2b2
aaa.a..bb..a.bb2
aaa.aaaaaaaa.b.2
.b..baaaaaab.b22
aa..bbaaaabb..2.
aaa.ab....ba....
aaaacaa..aaa....
aa.acaa..aaa....
.a..caa..aaa....
....aaa..aaa....
....aaa..aaa....
.....b....b.....
....aaa..aaa....
....aaa..aaa....
....aaa..aaa....
....aaa..aaa....
....aaa..aaa....
.....b....b.....
....bbb..bbb....
..bbbbb..bbbbb..
.bbbbbb..bbbbbb.
`;
            case "image24":
            case "Withered Foxy":return img`
222..........222
2ee2...2....2ee2
2ee2..2.2.2.2ee2
.22b...222..b22.
....2222ff22....
...fee2f22ee2...
.22ffff22211222.
..22ff22225122..
.222223ff322222.
.22223333332222.
...1c1b15b1c1...
....22222222....
.....222222.....
.......bb.......
..22.2dfbd2.22..
.2b22dbbddd22b2.
22222dfbfdd222f2
2bc.2dfbbdd2.cbf
fbc.2dfbbfd2.cfb
2fc.2dfbbfd2.c22
bbb.2ddbfdd2.bbb
222.22dddd22.222
.22..222222..22.
222.e..bb..e.222
.b..eeeeeeee..b.
ccc.beeeeeeb..b.
bbb.bbeeeebb..bb
.b..eb....be.bbb
b...eee..eeebbbb
b.b.eee..effbcbb
.b..bfe..ebf..b.
....fbe..efe....
....eee..eee....
.....b....b.....
.....f....f.....
.....b....b.....
.....b....b.....
.....f....f.....
.....b....b.....
.....b....b.....
....bbb..bbb....
..cbbcb..bcbbc..
.cbbbcb..bcbbbc.
`;
            case "image26":
            case "freddy charge 0":return img`
................................
................................
....ffff........................
....feef........................
....ceec........................
...ffbbff.......................
..eeeeeeee......................
.eeffeeeeee.....................
.ef1eeeeeee.....................
.e81eeeeeee.....................
.eeeeeeeeee.....................
ffdddeeeeee.....................
.1d1deeeeee.....................
.....bbeee......................
.1e1eeeee.......................
..eeeebbbb......................
......feccce....................
.....feceeece...................
....defeccceee..................
....ddeececeee..................
....ddeececeee..................
....ddeececeee..................
....deeebbbeee..................
.....eeececee...................
......eecece....................
.....e.bcec.e...................
.....eeececee...................
......eebbbe....................
......eecece....................
......eceeec....................
......ceeeec....................
......ecccec....................
......eeeece....................
........bb......................
......eeeec.....................
......eeeece....................
......eeeecee...................
......eeeeceee..................
......eeeeceeee.................
......eeeeceeee.................
.......eee.eeebbb...............
........bb....bbbee.............
.......ebbe...bbeeee............
......eeeee....eeee.............
.....eeeeee...eeee..............
`;
            case "image25":
            case "freddy charge 1":return img`
................................
................................
................................
....ffff........................
....feef........................
....ceec........................
...ffbbff.......................
..eeeeeeee......................
.eeffeeeeee.....................
.ef1eeeeeee.....................
.e81eeeeeee.....................
.eeeeeeeeee.....................
ffdddeeeeee.....................
.1d1deeeeee.....................
.....bbeee......................
.1e1eeeee.......................
..eeeebbbb......................
......feccce....................
.....feceeece...................
....defeccceee..................
....ddeececeee..................
....ddeececeee..................
....ddeececeee..................
....deeebbbeee..................
.....eeececee...................
......eecece....................
.....e.bcec.e...................
.....eeececee...................
......eebbbe....................
......eecece....................
......eceeec....................
......ceeeec....................
......ecccec....................
......eeeece....................
........bb......................
......eeeeceee..................
......eeeeceeee.................
......eeeeceeeee................
......eeeeceeeeee...............
......eeeec.eeeee...............
.......eee...eeebbb.............
........bb......bbbee...........
.......ebbe.....bbeeee..........
......eeeee......eeee...........
.....eeeeee.....eeee............
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "myAnim":
            case "anim1":return [img`
cccccccccccccfffffcccccccccccccc
cccccccccccccfffffcccccccccccccc
cccccccccccccfffffcccccccccccccc
cccceccccccccaaccacccccccceccccc
cccedeccccccfffffffccccccedecccc
ccedddecccceeeeeeeeeccccedddeccc
cccedebcceeeeeeeeeeeeeccbedecccc
ccccebcbeeeeeeeeeeeeeeebcbeccccc
ccccccbeffffeeeeeeeffffebccccccc
cccccceefffffeeeeefffffeeccccccc
cccccceeeeefffeeefffeeeeeccccccc
ccccceeee111eeeeeee111eeeecccccc
ccccceee18881eeeee18881eeecccccc
ccccceee18f81eeeee18f81eeecccccc
ccccceee18881eeeee18881eeecccccc
ccccceeee111eeeeeee111eeeecccccc
ccccceeeeeeeeeeeeeeeeeeeeecccccc
ccccceeeeeeeddfffddeeeeeeecccccc
ccccceeeeedddddfdddddeeeeecccccc
ccccceedddddddddddddddddeecccccc
ccccccdeddedddddddddeddedccccccc
ccccccdddedddddddddddedddccccccc
cccccccddddddeeeeeddddddcccccccc
ccccccccdddeeeeeeeeedddccccccccc
ccccccccceeeeeeeeeeeeecccccccccc
ccccccccccceeeeeeeeecccccccccccc
ccccccccccccbbcbcbbccccccccccccc
cccccccccccbcbcbcbcbcccccccccccc
ccccccceecbccbcbcbccbceecccccccc
cccccceeeceeefeeefeeeceeeccccccc
cccccceebeeeeefffeeeeebeeccccccc
cccceeeceeeddfdddfddeeeceeeccccc
`, img`
cccccccccccccfffffcccccccccccccc
cccccccccccccfffffcccccccccccccc
cccccccccccccfffffcccccccccccccc
cccceccccccccaaccacccccccceccccc
cccedeccccccfffffffccccccedecccc
ccedddecccceeeeeeeeeccccedddeccc
cccedebcceeeeeeeeeeeeeccbedecccc
ccccebcbeeeeeeeeeeeeeeebcbeccccc
ccccccbeffffeeeeeeeffffebccccccc
cccccceefffffeeeeefffffeeccccccc
cccccceeeeefffeeefffeeeeeccccccc
ccccceeeeeeeeeeeeeeeeeeeeecccccc
ccccceee18881eeeee18881eeecccccc
ccccceee18f81eeeee18f81eeecccccc
ccccceee18881eeeee18881eeecccccc
ccccceeeeeeeeeeeeeeeeeeeeecccccc
ccccceeeeeeeeeeeeeeeeeeeeecccccc
ccccceeeeeeeddfffddeeeeeeecccccc
ccccceeeeedddddfdddddeeeeecccccc
ccccceedddddddddddddddddeecccccc
ccccccdeddedddddddddeddedccccccc
ccccccdddedddddddddddedddccccccc
cccccccddddddeeeeeddddddcccccccc
ccccccccdddeeeeeeeeedddccccccccc
ccccccccceeeeeeeeeeeeecccccccccc
ccccccccccceeeeeeeeecccccccccccc
ccccccccccccbbcbcbbccccccccccccc
cccccccccccbcbcbcbcbcccccccccccc
ccccccceecbccbcbcbccbceecccccccc
cccccceeeceeefeeefeeeceeeccccccc
cccccceebeeeeefffeeeeebeeccccccc
cccceeeceeeddfdddfddeeeceeeccccc
`, img`
cccccccccccccfffffcccccccccccccc
cccccccccccccfffffcccccccccccccc
cccccccccccccfffffcccccccccccccc
cccceccccccccaaccacccccccceccccc
cccedeccccccfffffffccccccedecccc
ccedddecccceeeeeeeeeccccedddeccc
cccedebcceeeeeeeeeeeeeccbedecccc
ccccebcbeeeeeeeeeeeeeeebcbeccccc
ccccccbeffffeeeeeeeffffebccccccc
cccccceefffffeeeeefffffeeccccccc
cccccceeeeefffeeefffeeeeeccccccc
ccccceeeeeeeeeeeeeeeeeeeeecccccc
ccccceeeeeeeeeeeeeeeeeeeeecccccc
ccccceee18f81eeeee18f81eeecccccc
ccccceeeeeeeeeeeeeeeeeeeeecccccc
ccccceeeeeeeeeeeeeeeeeeeeecccccc
ccccceeeeeeeeeeeeeeeeeeeeecccccc
ccccceeeeeeeddfffddeeeeeeecccccc
ccccceeeeedddddfdddddeeeeecccccc
ccccceedddddddddddddddddeecccccc
ccccccdeddedddddddddeddedccccccc
ccccccdddedddddddddddedddccccccc
cccccccddddddeeeeeddddddcccccccc
ccccccccdddeeeeeeeeedddccccccccc
ccccccccceeeeeeeeeeeeecccccccccc
ccccccccccceeeeeeeeecccccccccccc
ccccccccccccbbcbcbbccccccccccccc
cccccccccccbcbcbcbcbcccccccccccc
ccccccceecbccbcbcbccbceecccccccc
cccccceeeceeefeeefeeeceeeccccccc
cccccceebeeeeefffeeeeebeeccccccc
cccceeeceeeddfdddfddeeeceeeccccc
`, img`
cccccccccccccfffffcccccccccccccc
cccccccccccccfffffcccccccccccccc
cccccccccccccfffffcccccccccccccc
cccceccccccccaaccacccccccceccccc
cccedeccccccfffffffccccccedecccc
ccedddecccceeeeeeeeeccccedddeccc
cccedebcceeeeeeeeeeeeeccbedecccc
ccccebcbeeeeeeeeeeeeeeebcbeccccc
ccccccbeffffeeeeeeeffffebccccccc
cccccceefffffeeeeefffffeeccccccc
cccccceeeeefffeeefffeeeeeccccccc
ccccceeeeeeeeeeeeeeeeeeeeecccccc
ccccceeeeeeeeeeeeeeeeeeeeecccccc
ccccceeeeeeeeeeeeeeeeeeeeecccccc
ccccceeeeeeeeeeeeeeeeeeeeecccccc
ccccceeeeeeeeeeeeeeeeeeeeecccccc
ccccceeeeeeeeeeeeeeeeeeeeecccccc
ccccceeeeeeeddfffddeeeeeeecccccc
ccccceeeeedddddfdddddeeeeecccccc
ccccceedddddddddddddddddeecccccc
ccccccdeddedddddddddeddedccccccc
ccccccdddedddddddddddedddccccccc
cccccccddddddeeeeeddddddcccccccc
ccccccccdddeeeeeeeeedddccccccccc
ccccccccceeeeeeeeeeeeecccccccccc
ccccccccccceeeeeeeeecccccccccccc
ccccccccccccbbcbcbbccccccccccccc
cccccccccccbcbcbcbcbcccccccccccc
ccccccceecbccbcbcbccbceecccccccc
cccccceeeceeefeeefeeeceeeccccccc
cccccceebeeeeefffeeeeebeeccccccc
cccceeeceeeddfdddfddeeeceeeccccc
`, img`
cccccccccccccfffffcccccccccccccc
cccccccccccccfffffcccccccccccccc
cccccccccccccfffffcccccccccccccc
cccceccccccccaaccacccccccceccccc
cccedeccccccfffffffccccccedecccc
ccedddecccceeeeeeeeeccccedddeccc
cccedebcceeeeeeeeeeeeeccbedecccc
ccccebcbeeeeeeeeeeeeeeebcbeccccc
ccccccbeffffeeeeeeeffffebccccccc
cccccceefffffeeeeefffffeeccccccc
cccccceeeeefffeeefffeeeeeccccccc
ccccceeeeeeeeeeeeeeeeeeeeecccccc
ccccceeeeeeeeeeeeeeeeeeeeecccccc
ccccceeeff1ffeeeeeff1ffeeecccccc
ccccceeeeeeeeeeeeeeeeeeeeecccccc
ccccceeeeeeeeeeeeeeeeeeeeecccccc
ccccceeeeeeeeeeeeeeeeeeeeecccccc
ccccceeeeeeeddfffddeeeeeeecccccc
ccccceeeeedddddfdddddeeeeecccccc
ccccceedddddddddddddddddeecccccc
ccccccdeddedddddddddeddedccccccc
ccccccdddedddddddddddedddccccccc
cccccccddddddeeeeeddddddcccccccc
ccccccccdddeeeeeeeeedddccccccccc
ccccccccceeeeeeeeeeeeecccccccccc
ccccccccccceeeeeeeeecccccccccccc
ccccccccccccbbcbcbbccccccccccccc
cccccccccccbcbcbcbcbcccccccccccc
ccccccceecbccbcbcbccbceecccccccc
cccccceeeceeefeeefeeeceeeccccccc
cccccceebeeeeefffeeeeebeeccccccc
cccceeeceeeddfdddfddeeeceeeccccc
`, img`
cccccccccccccfffffcccccccccccccc
cccccccccccccfffffcccccccccccccc
cccccccccccccfffffcccccccccccccc
cccceccccccccaaccacccccccceccccc
cccedeccccccfffffffccccccedecccc
ccedddecccceeeeeeeeeccccedddeccc
cccedebcceeeeeeeeeeeeeccbedecccc
ccccebcbeeeeeeeeeeeeeeebcbeccccc
ccccccbeffffeeeeeeeffffebccccccc
cccccceefffffeeeeefffffeeccccccc
cccccceeeeefffeeefffeeeeeccccccc
ccccceeeeeeeeeeeeeeeeeeeeecccccc
ccccceeefffffeeeeefffffeeecccccc
ccccceeeff1ffeeeeeff1ffeeecccccc
ccccceeefffffeeeeefffffeeecccccc
ccccceeeeeeeeeeeeeeeeeeeeecccccc
ccccceeeeeeeeeeeeeeeeeeeeecccccc
ccccceeeeeeeddfffddeeeeeeecccccc
ccccceeeeedddddfdddddeeeeecccccc
ccccceedddddddddddddddddeecccccc
ccccccdeddedddddddddeddedccccccc
ccccccdddedddddddddddedddccccccc
cccccccddddddeeeeeddddddcccccccc
ccccccccdddeeeeeeeeedddccccccccc
ccccccccceeeeeeeeeeeeecccccccccc
ccccccccccceeeeeeeeecccccccccccc
ccccccccccccbbcbcbbccccccccccccc
cccccccccccbcbcbcbcbcccccccccccc
ccccccceecbccbcbcbccbceecccccccc
cccccceeeceeefeeefeeeceeeccccccc
cccccceebeeeeefffeeeeebeeccccccc
cccceeeceeeddfdddfddeeeceeeccccc
`, img`
cccccccccccccfffffcccccccccccccc
cccccccccccccfffffcccccccccccccc
cccccccccccccfffffcccccccccccccc
cccceccccccccaaccacccccccceccccc
cccedeccccccfffffffccccccedecccc
ccedddecccceeeeeeeeeccccedddeccc
cccedebcceeeeeeeeeeeeeccbedecccc
ccccebcbeeeeeeeeeeeeeeebcbeccccc
ccccccbeffffeeeeeeeffffebccccccc
cccccceefffffeeeeefffffeeccccccc
cccccceeeeefffeeefffeeeeeccccccc
ccccceeeefffeeeeeeefffeeeecccccc
ccccceeefffffeeeeefffffeeecccccc
ccccceeeff1ffeeeeeff1ffeeecccccc
ccccceeefffffeeeeefffffeeecccccc
ccccceeeefffeeeeeeefffeeeecccccc
ccccceeeeeeeeeeeeeeeeeeeeecccccc
ccccceeeeeeeddfffddeeeeeeecccccc
ccccceeeeedddddfdddddeeeeecccccc
ccccceedddddddddddddddddeecccccc
ccccccdeddedddddddddeddedccccccc
ccccccdddedddddddddddedddccccccc
cccccccddddddeeeeeddddddcccccccc
ccccccccdddeeeeeeeeedddccccccccc
ccccccccceeeeeeeeeeeeecccccccccc
ccccccccccceeeeeeeeecccccccccccc
ccccccccccccbbcbcbbccccccccccccc
cccccccccccbcbcbcbcbcccccccccccc
ccccccceecbccbcbcbccbceecccccccc
cccccceeeceeefeeefeeeceeeccccccc
cccccceebeeeeefffeeeeebeeccccccc
cccceeeceeeddfdddfddeeeceeeccccc
`, img`
cccccccccccccfffffcccccccccccccc
cccccccccccccfffffcccccccccccccc
cccccccccccccfffffcccccccccccccc
cccceccccccccaaccacccccccceccccc
cccedeccccccfffffffccccccedecccc
ccedddecccceeeeeeeeeccccedddeccc
cccedebcceeeeeeeeeeeeeccbedecccc
ccccebcbeeeeeeeeeeeeeeebcbeccccc
ccccccbeffffeeeeeeeffffebccccccc
cccccceefffffeeeeefffffeeccccccc
cccccceeeeefffeeefffeeeeeccccccc
ccccceeeeeeeeeeeeeeeeeeeeecccccc
ccccceeefffffeeeeefffffeeecccccc
ccccceeeff1ffeeeeeff1ffeeecccccc
ccccceeefffffeeeeefffffeeecccccc
ccccceeeeeeeeeeeeeeeeeeeeecccccc
ccccceeeeeeeeeeeeeeeeeeeeecccccc
ccccceeeeeeeddfffddeeeeeeecccccc
ccccceeeeedddddfdddddeeeeecccccc
ccccceedddddddddddddddddeecccccc
ccccccdeddedddddddddeddedccccccc
ccccccdddedddddddddddedddccccccc
cccccccddddddeeeeeddddddcccccccc
ccccccccdddeeeeeeeeedddccccccccc
ccccccccceeeeeeeeeeeeecccccccccc
ccccccccccceeeeeeeeecccccccccccc
ccccccccccccbbcbcbbccccccccccccc
cccccccccccbcbcbcbcbcccccccccccc
ccccccceecbccbcbcbccbceecccccccc
cccccceeeceeefeeefeeeceeeccccccc
cccccceebeeeeefffeeeeebeeccccccc
cccceeeceeeddfdddfddeeeceeeccccc
`, img`
cccccccccccccfffffcccccccccccccc
cccccccccccccfffffcccccccccccccc
cccccccccccccfffffcccccccccccccc
cccceccccccccaaccacccccccceccccc
cccedeccccccfffffffccccccedecccc
ccedddecccceeeeeeeeeccccedddeccc
cccedebcceeeeeeeeeeeeeccbedecccc
ccccebcbeeeeeeeeeeeeeeebcbeccccc
ccccccbeffffeeeeeeeffffebccccccc
cccccceefffffeeeeefffffeeccccccc
cccccceeeeefffeeefffeeeeeccccccc
ccccceeeeeeeeeeeeeeeeeeeeecccccc
ccccceeeeeeeeeeeeeeeeeeeeecccccc
ccccceeeff1ffeeeeeff1ffeeecccccc
ccccceeeeeeeeeeeeeeeeeeeeecccccc
ccccceeeeeeeeeeeeeeeeeeeeecccccc
ccccceeeeeeeeeeeeeeeeeeeeecccccc
ccccceeeeeeeddfffddeeeeeeecccccc
ccccceeeeedddddfdddddeeeeecccccc
ccccceedddddddddddddddddeecccccc
ccccccdeddedddddddddeddedccccccc
ccccccdddedddddddddddedddccccccc
cccccccddddddeeeeeddddddcccccccc
ccccccccdddeeeeeeeeedddccccccccc
ccccccccceeeeeeeeeeeeecccccccccc
ccccccccccceeeeeeeeecccccccccccc
ccccccccccccbbcbcbbccccccccccccc
cccccccccccbcbcbcbcbcccccccccccc
ccccccceecbccbcbcbccbceecccccccc
cccccceeeceeefeeefeeeceeeccccccc
cccccceebeeeeefffeeeeebeeccccccc
cccceeeceeeddfdddfddeeeceeeccccc
`, img`
cccccccccccccfffffcccccccccccccc
cccccccccccccfffffcccccccccccccc
cccccccccccccfffffcccccccccccccc
cccceccccccccaaccacccccccceccccc
cccedeccccccfffffffccccccedecccc
ccedddecccceeeeeeeeeccccedddeccc
cccedebcceeeeeeeeeeeeeccbedecccc
ccccebcbeeeeeeeeeeeeeeebcbeccccc
ccccccbeffffeeeeeeeffffebccccccc
cccccceefffffeeeeefffffeeccccccc
cccccceeeeefffeeefffeeeeeccccccc
ccccceeeeeeeeeeeeeeeeeeeeecccccc
ccccceeeeeeeeeeeeeeeeeeeeecccccc
ccccceeeeeeeeeeeeeeeeeeeeecccccc
ccccceeeeeeeeeeeeeeeeeeeeecccccc
ccccceeeeeeeeeeeeeeeeeeeeecccccc
ccccceeeeeeeeeeeeeeeeeeeeecccccc
ccccceeeeeeeddfffddeeeeeeecccccc
ccccceeeeedddddfdddddeeeeecccccc
ccccceedddddddddddddddddeecccccc
ccccccdeddedddddddddeddedccccccc
ccccccdddedddddddddddedddccccccc
cccccccddddddeeeeeddddddcccccccc
ccccccccdddeeeeeeeeedddccccccccc
ccccccccceeeeeeeeeeeeecccccccccc
ccccccccccceeeeeeeeecccccccccccc
ccccccccccccbbcbcbbccccccccccccc
cccccccccccbcbcbcbcbcccccccccccc
ccccccceecbccbcbcbccbceecccccccc
cccccceeeceeefeeefeeeceeeccccccc
cccccceebeeeeefffeeeeebeeccccccc
cccceeeceeeddfdddfddeeeceeeccccc
`, img`
cccccccccccccfffffcccccccccccccc
cccccccccccccfffffcccccccccccccc
cccccccccccccfffffcccccccccccccc
cccceccccccccaaccacccccccceccccc
cccedeccccccfffffffccccccedecccc
ccedddecccceeeeeeeeeccccedddeccc
cccedebcceeeeeeeeeeeeeccbedecccc
ccccebcbeeeeeeeeeeeeeeebcbeccccc
ccccccbeffffeeeeeeeffffebccccccc
cccccceefffffeeeeefffffeeccccccc
cccccceeeeefffeeefffeeeeeccccccc
ccccceeeeeeeeeeeeeeeeeeeeecccccc
ccccceeeeeeeeeeeeeeeeeeeeecccccc
ccccceee18f81eeeee18f81eeecccccc
ccccceeeeeeeeeeeeeeeeeeeeecccccc
ccccceeeeeeeeeeeeeeeeeeeeecccccc
ccccceeeeeeeeeeeeeeeeeeeeecccccc
ccccceeeeeeeddfffddeeeeeeecccccc
ccccceeeeedddddfdddddeeeeecccccc
ccccceedddddddddddddddddeecccccc
ccccccdeddedddddddddeddedccccccc
ccccccdddedddddddddddedddccccccc
cccccccddddddeeeeeddddddcccccccc
ccccccccdddeeeeeeeeedddccccccccc
ccccccccceeeeeeeeeeeeecccccccccc
ccccccccccceeeeeeeeecccccccccccc
ccccccccccccbbcbcbbccccccccccccc
cccccccccccbcbcbcbcbcccccccccccc
ccccccceecbccbcbcbccbceecccccccc
cccccceeeceeefeeefeeeceeeccccccc
cccccceebeeeeefffeeeeebeeccccccc
cccceeeceeeddfdddfddeeeceeeccccc
`, img`
cccccccccccccfffffcccccccccccccc
cccccccccccccfffffcccccccccccccc
cccccccccccccfffffcccccccccccccc
cccceccccccccaaccacccccccceccccc
cccedeccccccfffffffccccccedecccc
ccedddecccceeeeeeeeeccccedddeccc
cccedebcceeeeeeeeeeeeeccbedecccc
ccccebcbeeeeeeeeeeeeeeebcbeccccc
ccccccbeffffeeeeeeeffffebccccccc
cccccceefffffeeeeefffffeeccccccc
cccccceeeeefffeeefffeeeeeccccccc
ccccceeeeeeeeeeeeeeeeeeeeecccccc
ccccceee18881eeeee18881eeecccccc
ccccceee18f81eeeee18f81eeecccccc
ccccceee18881eeeee18881eeecccccc
ccccceeeeeeeeeeeeeeeeeeeeecccccc
ccccceeeeeeeeeeeeeeeeeeeeecccccc
ccccceeeeeeeddfffddeeeeeeecccccc
ccccceeeeedddddfdddddeeeeecccccc
ccccceedddddddddddddddddeecccccc
ccccccdeddedddddddddeddedccccccc
ccccccdddedddddddddddedddccccccc
cccccccddddddeeeeeddddddcccccccc
ccccccccdddeeeeeeeeedddccccccccc
ccccccccceeeeeeeeeeeeecccccccccc
ccccccccccceeeeeeeeecccccccccccc
ccccccccccccbbcbcbbccccccccccccc
cccccccccccbcbcbcbcbcccccccccccc
ccccccceecbccbcbcbccbceecccccccc
cccccceeeceeefeeefeeeceeeccccccc
cccccceebeeeeefffeeeeebeeccccccc
cccceeeceeeddfdddfddeeeceeeccccc
`, img`
cccccccccccccfffffcccccccccccccc
cccccccccccccfffffcccccccccccccc
cccccccccccccfffffcccccccccccccc
cccceccccccccaaccacccccccceccccc
cccedeccccccfffffffccccccedecccc
ccedddecccceeeeeeeeeccccedddeccc
cccedebcceeeeeeeeeeeeeccbedecccc
ccccebcbeeeeeeeeeeeeeeebcbeccccc
ccccccbeffffeeeeeeeffffebccccccc
cccccceefffffeeeeefffffeeccccccc
cccccceeeeefffeeefffeeeeeccccccc
ccccceeee111eeeeeee111eeeecccccc
ccccceee18881eeeee18881eeecccccc
ccccceee18f81eeeee18f81eeecccccc
ccccceee18881eeeee18881eeecccccc
ccccceeee111eeeeeee111eeeecccccc
ccccceeeeeeeeeeeeeeeeeeeeecccccc
ccccceeeeeeeddfffddeeeeeeecccccc
ccccceeeeedddddfdddddeeeeecccccc
ccccceedddddddddddddddddeecccccc
ccccccdeddedddddddddeddedccccccc
ccccccdddedddddddddddedddccccccc
cccccccddddddeeeeeddddddcccccccc
ccccccccdddeeeeeeeeedddccccccccc
ccccccccceeeeeeeeeeeeecccccccccc
ccccccccccceeeeeeeeecccccccccccc
ccccccccccccbbcbcbbccccccccccccc
cccccccccccbcbcbcbcbcccccccccccc
ccccccceecbccbcbcbccbceecccccccc
cccccceeeceeefeeefeeeceeeccccccc
cccccceebeeeeefffeeeeebeeccccccc
cccceeeceeeddfdddfddeeeceeeccccc
`];
            case "Jumpscare":
            case "anim2":return [img`
ccccccccccccccfffffccccccccccccc
ccccccccccccccfffffccccccccccccc
ccccccccccccccfffffccccccccccccc
ccccccccccccccfffffccccccccccccc
ccccceeeccccccfffffcccccceeecccc
ccccceddeccccfffffffcccceddecccc
ccccceddbccceeeeeeeeecccbddecccc
ccccccebcbeeeeeeeeeeeeebcbeccccc
ccccccccbeffeeeeeeeeeffebccccccc
cccccccceeefffeeeeefffeeeccccccc
cccccccceeeefffeeefffeeeeccccccc
ccccccceeee111eeeee111eeeecccccc
ccccccceee18881eee18881eeecccccc
ccccccceee18f81eee18f81eeecccccc
ccccccceee18881eee18881eeecccccc
ccccccceeee111eeeee111eeeecccccc
ccccccceeeeeeeeeeeeeeeeeeecccccc
ccccccceeeddddfffffddddeeecccccc
cccccceeeddddddfffddddddeeeccccc
cccccccdddedddddddddddedddcccccc
cccccccdeddcccbbbbbcccddedcccccc
cccccccddeccccbbbbbcccceddcccccc
cccccccccc12221ccc12221ccccccccc
cccccccccc1222111112221ccccccccc
cccccccccce22222222222eccccccccc
cccccccccce11e11e11e11eccccccccc
cccccccccccceeeeeeeeeccccccccccc
cccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccc
`, img`
cccccccccccccfffffffcccccccccccc
cccccccccccccfffffffcccccccccccc
cccccccccccccfffffffcccccccccccc
cccccccccccccfffffffcccccccccccc
cccceeeccccccfffffffcccccceeeccc
cccceddeccccfffffffffcccceddeccc
cccceddbccceeeeeeeeeeecccbddeccc
cccccebcbeeeeeeeeeeeeeeebcbecccc
cccccccbeffeeeeeeeeeeeffebcccccc
ccccccceeefffeeeeeeefffeeecccccc
ccccccceeeefffeeeeefffeeeecccccc
ccccccceeeeeffeeeeeffeeeeecccccc
ccccccceeeeeeeeeeeeeeeeeeecccccc
cccccceeee111eeeeeee111eeeeccccc
cccccceee18881eeeee18881eeeccccc
cccccceee18f81eeeee18f81eeeccccc
cccccceee18881eeeee18881eeeccccc
cccccceeee111eeeeeee111eeeeccccc
cccccceeeeeeeeeeeeeeeeeeeeeccccc
cccccceeeddddfffffffddddeeeccccc
ccccceeeddddddfffffddddddeeecccc
ccccceeedddddddddddddddddeeecccc
ccccceeedddddddddddddddddeeecccc
ccccccdddedddddddddddddedddccccc
ccccccdeddcccbbbbbbbcccddedccccc
ccccccddeccccbbbbbbbcccceddccccc
ccccccccc12221ccccc12221cccccccc
ccccccccc122211111112221cccccccc
ccccccccce2222222222222ecccccccc
ccccccccce11e1111e11e11ecccccccc
ccccccccccceeeeeeeeeeecccccccccc
cccccccccccccccccccccccccccccccc
`];
            case "Jumpscare0":
            case "anim3":return [img`
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccbcccccc3344499ccccccccccccccccccccccccccfcccccccccccc
cccccccccbbbccccccafacfffccccccccccccccccccccccccccfffcccccccccc
cccccccbbbbbccccccfafef5fccccccccccccccccccccccccccfffffcccccccc
cccccbbbbbbbccccccf2fcf1fccccccccccccccccccccccccccfffffffcccccc
cccbbbbbbbbbccccccfafef5fccccccccccccccccccccccccccfffffffffcccc
cbbbbbbbbbbbccccccfafef5fccccccccccccccccccccccccccfffffffffffcc
cbbbbbbbbbbbcccccc1f11f11ccccccccccccccccccccccccccffffffffffffc
cbbbbbbbbbbbccccccf1ff1ffccccccccccccccccccccccccccffffffffffffc
cbbbbbbbbbbbccccccfffffffccccccccccccccccccccccccccffffffffffffc
cbbbbbbbbbbbccccccccccccccccccccbbbccccbbccccccccccffffffffffffc
cbbbbbbbbbbbccccccccccccccccccccbfbcccbffbcccccccccffffffffffffc
cbbbbbbbbbbbccccccccccccccccccccbbbcccbffbcccccccccffffffffffffc
cbbbbbbbbbbbccccccccccccccccccbbbcbbbccbbccccccccccffffffffffffc
cbbbbbbbbbbbccccccccccccccccccbfbcbfbccffccccccccccffffffffffffc
cbbbbbbbbbbbccccccccccccccccccbbbcbbbcffffcccccccccffffffffffffc
cbbbbbbbbbbbcccccceeeeeeeeeeeeeeeeeeeeeeeeeeeccccccffffffffffffc
cbbbbbbbbbbbcccccceeeeeeeeeeeeeeeeeeeeeeeeeeeccccccffffffffffffc
cbbbbbbbbbbbcccccceeceeccccccccccccccccceeceeccccccffffffffffffc
cbbbbbbbbb55cccccceeceeccccccccccccccccceeceeccccccffffffffffffc
cbbbbbbbbb55cccccceeceeccccccccccccccccceeceeccccccffffffffffffc
cbbbbbbfff55cccccceeceeccccccccccccccccceeceeccccccffffffffffffc
cbbbbbbfffcccccccceeceeccccccccccccccccceeceeccccccffffffffffffc
cbbbb55ccccccccccceeccccccccccccccccccccccceeccccccccffffffffffc
c55ff55ccccccccccccccccccccccccccccccccccccccccccccccccffffffffc
c55ffccccccccccccccccccccccccccccccccccccccccccccccccccccffffffc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
`, img`
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccbcccccc3344499ccccccccccccccccccccccccccfcccccccccccc
cccccccccbbbccccccafacfffccccccccccccccccccccccccccfffcccccccccc
cccccccbbbbbccccccfafef5fccccccccccccccccccccccccccfffffcccccccc
cccccbbbbbbbccccccf2fcf1fccccccccccccccccccccccccccfffffffcccccc
cccbbbbbbbbbccccccfafef5fccccccccccccccccccccccccccfffffffffcccc
cbbbbbbbbbbbccccccfafef5fccccccccccccccccccccccccccfffffffffffcc
cbbbbbbbbbbbcccccc1f11f11ccccccccccccccccccccccccccffffffffffffc
cbbbbbbbbbbbccccccf1ff1ffccccccccccccccccccccccccccfffbffffffffc
cbbbbbbbbbbbccccccfffffffccccccccccccccccccccccccccfffbbfffbfffc
cbbbbbbbbbbbccccccccccccccccccccbbbccccbbccccccccccfffffffbbfffc
cbbbbbbbbbbbccccccccccccccccccccbfbcccbffbcccccccccffffffffffffc
cbbbbbbbbbbbccccccccccccccccccccbbbcccbffbcccccccccffffffffffffc
cbbbbbbbbbbbccccccccccccccccccbbbcbbbccbbccccccccccfffbfbbfbfffc
cbbbbbbbbbbbccccccccccccccccccbfbcbfbccffccccccccccffffffffffffc
cbbbbbbbbbbbccccccccccccccccccbbbcbbbcffffcccccccccfffffbbfffffc
cbbbbbbbbbbbcccccceeeeeeeeeeeeeeeeeeeeeeeeeeeccccccffffffffffffc
cbbbbbbbbbbbcccccceeeeeeeeeeeeeeeeeeeeeeeeeeeccccccffffffffffffc
cbbbbbbbbbbbcccccceeceeccccccccccccccccceeceeccccccffffffffffffc
cbbbbbbbbb55cccccceeceeccccccccccccccccceeceeccccccffffffffffffc
cbbbbbbbbb55cccccceeceeccccccccccccccccceeceeccccccffffffffffffc
cbbbbbbfff55cccccceeceeccccccccccccccccceeceeccccccffffffffffffc
cbbbbbbfffcccccccceeceeccccccccccccccccceeceeccccccffffffffffffc
cbbbb55ccccccccccceeccccccccccccccccccccccceeccccccccffffffffffc
c55ff55ccccccccccccccccccccccccccccccccccccccccccccccccffffffffc
c55ffccccccccccccccccccccccccccccccccccccccccccccccccccccffffffc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
`, img`
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccbcccccc3344499ccccccccccccccccccccccccccfcccccccccccc
cccccccccbbbccccccafacfffccccccccccccccccccccccccccfffcccccccccc
cccccccbbbbbccccccfafef5fccccccccccccccccccccccccccfffffcccccccc
cccccbbbbbbbccccccf2fcf1fccccccccccccccccccccccccccfffffffcccccc
cccbbbbbbbbbccccccfafef5fccccccccccccccccccccccccccfffffffffcccc
cbbbbbbbbbbbccccccfafef5fccccccccccccccccccccccccccfffffffffffcc
cbbbbbbbbbbbcccccc1f11f11ccccccccccccccccccccccccccffffffffffffc
cbbbbbbbbbbbccccccf1ff1ffccccccccccccccccccccccccccfff1ffffffffc
cbbbbbbbbbbbccccccfffffffccccccccccccccccccccccccccfff1bfff1fffc
cbbbbbbbbbbbccccccccccccccccccccbbbccccbbccccccccccfffffffb1fffc
cbbbbbbbbbbbccccccccccccccccccccbfbcccbffbcccccccccffffffffffffc
cbbbbbbbbbbbccccccccccccccccccccbbbcccbffbcccccccccffffffffffffc
cbbbbbbbbbbbccccccccccccccccccbbbcbbbccbbccccccccccfff1f11f1fffc
cbbbbbbbbbbbccccccccccccccccccbfbcbfbccffccccccccccffffffffffffc
cbbbbbbbbbbbccccccccccccccccccbbbcbbbcffffcccccccccfffff11fffffc
cbbbbbbbbbbbcccccceeeeeeeeeeeeeeeeeeeeeeeeeeeccccccffffffffffffc
cbbbbbbbbbbbcccccceeeeeeeeeeeeeeeeeeeeeeeeeeeccccccffffffffffffc
cbbbbbbbbbbbcccccceeceeccccccccccccccccceeceeccccccffffffffffffc
cbbbbbbbbb55cccccceeceeccccccccccccccccceeceeccccccffffffffffffc
cbbbbbbbbb55cccccceeceeccccccccccccccccceeceeccccccffffffffffffc
cbbbbbbfff55cccccceeceeccccccccccccccccceeceeccccccffffffffffffc
cbbbbbbfffcccccccceeceeccccccccccccccccceeceeccccccffffffffffffc
cbbbb55ccccccccccceeccccccccccccccccccccccceeccccccccffffffffffc
c55ff55ccccccccccccccccccccccccccccccccccccccccccccccccffffffffc
c55ffccccccccccccccccccccccccccccccccccccccccccccccccccccffffffc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
`, img`
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccbcccccc3344499ccccccccccccccccccccccccccfcccccccccccc
cccccccccbbbccccccafacfffccccccccccccccccccccccccccfffcccccccccc
cccccccbbbbbccccccfafef5fccccccccccccccccccccccccccfffffcccccccc
cccccbbbbbbbccccccf2fcf1fccccccccccccccccccccccccccfffffffcccccc
cccbbbbbbbbbccccccfafef5fccccccccccccccccccccccccccfffffffffcccc
cbbbbbbbbbbbccccccfafef5fccccccccccccccccccccccccccfffffffffffcc
cbbbbbbbbbbbcccccc1f11f11ccccccccccccccccccccccccccffffffffffffc
cbbbbbbbbbbbccccccf1ff1ffccccccccccccccccccccccccccfff1ffffffffc
cbbbbbbbbbbbccccccfffffffccccccccccccccccccccccccccfff1bfff1fffc
cbbbbbbbbbbbccccccccccccccccccccbbbccccbbccccccccccfffffffb1fffc
cbbbbbbbbbbbccccccccccccccccccccbfbcccbffbcccccccccffffffffffffc
cbbbbbbbbbbbccccccccccccccccccccbbbcccbffbcccccccccffffffffffffc
cbbbbbbbbbbbccccccccccccccccccbbbcbbbccbbccccccccccfff1f11f1fffc
cbbbbbbbbbbbccccccccccccccccccbfbcbfbccffccccccccccffffffffffffc
cbbbbbbbbbbbccccccccccccccccccbbbcbbbcffffcccccccccfffff11fffffc
cbbbbbbbbbbbcccccceeeeeeeeeeeeeeeeeeeeeeeeeeeccccccffffffffffffc
cbbbbbbbbbbbcccccceeeeeeeeeeeeeeeeeeeeeeeeeeeccccccffffffffffffc
cbbbbbbbbbbbcccccceeceeccccccccccccccccceeceeccccccffffffffffffc
cbbbbbbbbb55cccccceeceeccccccccccccccccceeceeccccccffffffffffffc
cbbbbbbbbb55cccccceeceeccccccccccccccccceeceeccccccffffffffffffc
cbbbbbbfff55cccccceeceeccccccccccccccccceeceeccccccffffffffffffc
cbbbbbbfffcccccccceeceeccccccccccccccccceeceeccccccffffffffffffc
cbbbb55ccccccccccceeccccccccccccccccccccccceeccccccccffffffffffc
c55ff55ccccccccccccccccccccccccccccccccccccccccccccccccffffffffc
c55ffccccccccccccccccccccccccccccccccccccccccccccccccccccffffffc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
`, img`
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccbcccccc3344499ccccccccccccccccccccccccccfcccccccccccc
cccccccccbbbccccccafacfffccccccccccccccccccccccccccfffcccccccccc
cccccccbbbbbccccccfafef5fccccccccccccccccccccccccccfffffcccccccc
cccccbbbbbbbccccccf2fcf1fccccccccccccccccccccccccccfffffffcccccc
cccbbbbbbbbbccccccfafef5fccccccccccccccccccccccccccfffffffffcccc
cbbbbbbbbbbbccccccfafef5fccccccccccccccccccccccccccfffffffffffcc
cbbbbbbbbbbbcccccc1f11f11ccccccccccccccccccccccccccffffffffffffc
cbbbbbbbbbbbccccccf1ff1ffccccccccccccccccccccccccccfffbffffffffc
cbbbbbbbbbbbccccccfffffffccccccccccccccccccccccccccfffbbfffbfffc
cbbbbbbbbbbbccccccccccccccccccccbbbccccbbccccccccccfffffffbbfffc
cbbbbbbbbbbbccccccccccccccccccccbfbcccbffbcccccccccffffffffffffc
cbbbbbbbbbbbccccccccccccccccccccbbbcccbffbcccccccccffffffffffffc
cbbbbbbbbbbbccccccccccccccccccbbbcbbbccbbccccccccccfffbfbbfbfffc
cbbbbbbbbbbbccccccccccccccccccbfbcbfbccffccccccccccffffffffffffc
cbbbbbbbbbbbccccccccccccccccccbbbcbbbcffffcccccccccfffffbbfffffc
cbbbbbbbbbbbcccccceeeeeeeeeeeeeeeeeeeeeeeeeeeccccccffffffffffffc
cbbbbbbbbbbbcccccceeeeeeeeeeeeeeeeeeeeeeeeeeeccccccffffffffffffc
cbbbbbbbbbbbcccccceeceeccccccccccccccccceeceeccccccffffffffffffc
cbbbbbbbbb55cccccceeceeccccccccccccccccceeceeccccccffffffffffffc
cbbbbbbbbb55cccccceeceeccccccccccccccccceeceeccccccffffffffffffc
cbbbbbbfff55cccccceeceeccccccccccccccccceeceeccccccffffffffffffc
cbbbbbbfffcccccccceeceeccccccccccccccccceeceeccccccffffffffffffc
cbbbb55ccccccccccceeccccccccccccccccccccccceeccccccccffffffffffc
c55ff55ccccccccccccccccccccccccccccccccccccccccccccccccffffffffc
c55ffccccccccccccccccccccccccccccccccccccccccccccccccccccffffffc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
`, img`
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccbcccccc3344499ccccccccccccccccccccccccccfcccccccccccc
cccccccccbbbccccccafacfffccccccccccccccccccccccccccfffcccccccccc
cccccccbbbbbccccccfafef5fccccccccccccccccccccccccccfffffcccccccc
cccccbbbbbbbccccccf2fcf1fccccccccccccccccccccccccccfffffffcccccc
cccbbbbbbbbbccccccfafef5fccccccccccccccccccccccccccfffffffffcccc
cbbbbbbbbbbbccccccfafef5fccccccccccccccccccccccccccfffffffffffcc
cbbbbbbbbbbbcccccc1f11f11ccccccccccccccccccccccccccffffffffffffc
cbbbbbbbbbbbccccccf1ff1ffccccccccccccccccccccccccccffffffffffffc
cbbbbbbbbbbbccccccfffffffccccccccccccccccccccccccccffffffffffffc
cbbbbbbbbbbbccccccccccccccccccccbbbccccbbccccccccccffffffffffffc
cbbbbbbbbbbbccccccccccccccccccccbfbcccbffbcccccccccffffffffffffc
cbbbbbbbbbbbccccccccccccccccccccbbbcccbffbcccccccccffffffffffffc
cbbbbbbbbbbbccccccccccccccccccbbbcbbbccbbccccccccccffffffffffffc
cbbbbbbbbbbbccccccccccccccccccbfbcbfbccffccccccccccffffffffffffc
cbbbbbbbbbbbccccccccccccccccccbbbcbbbcffffcccccccccffffffffffffc
cbbbbbbbbbbbcccccceeeeeeeeeeeeeeeeeeeeeeeeeeeccccccffffffffffffc
cbbbbbbbbbbbcccccceeeeeeeeeeeeeeeeeeeeeeeeeeeccccccffffffffffffc
cbbbbbbbbbbbcccccceeceeccccccccccccccccceeceeccccccffffffffffffc
cbbbbbbbbb55cccccceeceeccccccccccccccccceeceeccccccffffffffffffc
cbbbbbbbbb55cccccceeceeccccccccccccccccceeceeccccccffffffffffffc
cbbbbbbfff55cccccceeceeccccccccccccccccceeceeccccccffffffffffffc
cbbbbbbfffcccccccceeceeccccccccccccccccceeceeccccccffffffffffffc
cbbbb55ccccccccccceeccccccccccccccccccccccceeccccccccffffffffffc
c55ff55ccccccccccccccccccccccccccccccccccccccccccccccccffffffffc
c55ffccccccccccccccccccccccccccccccccccccccccccccccccccccffffffc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
`, img`
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccbcccccc3344499ccccccccccccccccccccccccccfcccccccccccc
cccccccccbbbccccccafacfffccccccccccccccccccccccccccfffcccccccccc
cccccccbbbbbccccccfafef5fccccccccccccccccccccccccccfffffcccccccc
cccccbbbbbbbccccccf2fcf1fccccccccccccccccccccccccccfffffffcccccc
cccbbbbbbbbbccccccfafef5fccccccccccccccccccccccccccfffffffffcccc
cbbbbbbbbbbbccccccfafef5fccccccccccccccccccccccccccfffffffffffcc
cbbbbbbbbbbbcccccc1f11f11ccccccccccccccccccccccccccffffffffffffc
cbbbbbbbbbbbccccccf1ff1ffccccccccccccccccccccccccccfffbffffffffc
cbbbbbbbbbbbccccccfffffffccccccccccccccccccccccccccfffbbfffbfffc
cbbbbbbbbbbbccccccccccccccccccccbbbccccbbccccccccccfffffffbbfffc
cbbbbbbbbbbbccccccccccccccccccccbfbcccbffbcccccccccffffffffffffc
cbbbbbbbbbbbccccccccccccccccccccbbbcccbffbcccccccccffffffffffffc
cbbbbbbbbbbbccccccccccccccccccbbbcbbbccbbccccccccccfffbfbbfbfffc
cbbbbbbbbbbbccccccccccccccccccbfbcbfbccffccccccccccffffffffffffc
cbbbbbbbbbbbccccccccccccccccccbbbcbbbcffffcccccccccfffffbbfffffc
cbbbbbbbbbbbcccccceeeeeeeeeeeeeeeeeeeeeeeeeeeccccccffffffffffffc
cbbbbbbbbbbbcccccceeeeeeeeeeeeeeeeeeeeeeeeeeeccccccffffffffffffc
cbbbbbbbbbbbcccccceeceeccccccccccccccccceeceeccccccffffffffffffc
cbbbbbbbbb55cccccceeceeccccccccccccccccceeceeccccccffffffffffffc
cbbbbbbbbb55cccccceeceeccccccccccccccccceeceeccccccffffffffffffc
cbbbbbbfff55cccccceeceeccccccccccccccccceeceeccccccffffffffffffc
cbbbbbbfffcccccccceeceeccccccccccccccccceeceeccccccffffffffffffc
cbbbb55ccccccccccceeccccccccccccccccccccccceeccccccccffffffffffc
c55ff55ccccccccccccccccccccccccccccccccccccccccccccccccffffffffc
c55ffccccccccccccccccccccccccccccccccccccccccccccccccccccffffffc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
`, img`
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccbcccccc3344499ccccccccccccccccccccccccccfcccccccccccc
cccccccccbbbccccccafacfffccccccccccccccccccccccccccfffcccccccccc
cccccccbbbbbccccccfafef5fccccccccccccccccccccccccccfffffcccccccc
cccccbbbbbbbccccccf2fcf1fccccccccccccccccccccccccccfffffffcccccc
cccbbbbbbbbbccccccfafef5fccccccccccccccccccccccccccfffffffffcccc
cbbbbbbbbbbbccccccfafef5fccccccccccccccccccccccccccfffffffffffcc
cbbbbbbbbbbbcccccc1f11f11ccccccccccccccccccccccccccffffffffffffc
cbbbbbbbbbbbccccccf1ff1ffccccccccccccccccccccccccccfff1ffffffffc
cbbbbbbbbbbbccccccfffffffccccccccccccccccccccccccccfff1bfff1fffc
cbbbbbbbbbbbccccccccccccccccccccbbbccccbbccccccccccfffffffb1fffc
cbbbbbbbbbbbccccccccccccccccccccbfbcccbffbcccccccccffffffffffffc
cbbbbbbbbbbbccccccccccccccccccccbbbcccbffbcccccccccffffffffffffc
cbbbbbbbbbbbccccccccccccccccccbbbcbbbccbbccccccccccfff1f11f1fffc
cbbbbbbbbbbbccccccccccccccccccbfbcbfbccffccccccccccffffffffffffc
cbbbbbbbbbbbccccccccccccccccccbbbcbbbcffffcccccccccfffff11fffffc
cbbbbbbbbbbbcccccceeeeeeeeeeeeeeeeeeeeeeeeeeeccccccffffffffffffc
cbbbbbbbbbbbcccccceeeeeeeeeeeeeeeeeeeeeeeeeeeccccccffffffffffffc
cbbbbbbbbbbbcccccceeceeccccccccccccccccceeceeccccccffffffffffffc
cbbbbbbbbb55cccccceeceeccccccccccccccccceeceeccccccffffffffffffc
cbbbbbbbbb55cccccceeceeccccccccccccccccceeceeccccccffffffffffffc
cbbbbbbfff55cccccceeceeccccccccccccccccceeceeccccccffffffffffffc
cbbbbbbfffcccccccceeceeccccccccccccccccceeceeccccccffffffffffffc
cbbbb55ccccccccccceeccccccccccccccccccccccceeccccccccffffffffffc
c55ff55ccccccccccccccccccccccccccccccccccccccccccccccccffffffffc
c55ffccccccccccccccccccccccccccccccccccccccccccccccccccccffffffc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
`, img`
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccbcccccc3344499ccccccccccccccccccccccccccfcccccccccccc
cccccccccbbbccccccafacfffccccccccccccccccccccccccccfffcccccccccc
cccccccbbbbbccccccfafef5fccccccccccccccccccccccccccfffffcccccccc
cccccbbbbbbbccccccf2fcf1fccccccccccccccccccccccccccfffffffcccccc
cccbbbbbbbbbccccccfafef5fccccccccccccccccccccccccccfffffffffcccc
cbbbbbbbbbbbccccccfafef5fccccccccccccccccccccccccccfffffffffffcc
cbbbbbbbbbbbcccccc1f11f11ccccccccccccccccccccccccccffffffffffffc
cbbbbbbbbbbbccccccf1ff1ffccccccccccccccccccccccccccfff1ffffffffc
cbbbbbbbbbbbccccccfffffffccccccccccccccccccccccccccfff1bfff1fffc
cbbbbbbbbbbbccccccccccccccccccccbbbccccbbccccccccccfffffffb1fffc
cbbbbbbbbbbbccccccccccccccccccccbfbcccbffbcccccccccffffffffffffc
cbbbbbbbbbbbccccccccccccccccccccbbbcccbffbcccccccccffffffffffffc
cbbbbbbbbbbbccccccccccccccccccbbbcbbbccbbccccccccccfff1f11f1fffc
cbbbbbbbbbbbccccccccccccccccccbfbcbfbccffccccccccccffffffffffffc
cbbbbbbbbbbbccccccccccccccccccbbbcbbbcffffcccccccccfffff11fffffc
cbbbbbbbbbbbcccccceeeeeeeeeeeeeeeeeeeeeeeeeeeccccccffffffffffffc
cbbbbbbbbbbbcccccceeeeeeeeeeeeeeeeeeeeeeeeeeeccccccffffffffffffc
cbbbbbbbbbbbcccccceeceeccccccccccccccccceeceeccccccffffffffffffc
cbbbbbbbbb55cccccceeceeccccccccccccccccceeceeccccccffffffffffffc
cbbbbbbbbb55cccccceeceeccccccccccccccccceeceeccccccffffffffffffc
cbbbbbbfff55cccccceeceeccccccccccccccccceeceeccccccffffffffffffc
cbbbbbbfffcccccccceeceeccccccccccccccccceeceeccccccffffffffffffc
cbbbb55ccccccccccceeccccccccccccccccccccccceeccccccccffffffffffc
c55ff55ccccccccccccccccccccccccccccccccccccccccccccccccffffffffc
c55ffccccccccccccccccccccccccccccccccccccccccccccccccccccffffffc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
`, img`
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccbcccccc3344499ccccccccccccccccccccccccccfcccccccccccc
cccccccccbbbccccccafacfffccccccccccccccccccccccccccfffcccccccccc
cccccccbbbbbccccccfafef5fccccccccccccccccccccccccccfffffcccccccc
cccccbbbbbbbccccccf2fcf1fccccccccccccccccccccccccccfffffffcccccc
cccbbbbbbbbbccccccfafef5fccccccccccccccccccccccccccfffffffffcccc
cbbbbbbbbbbbccccccfafef5fccccccccccccccccccccccccccfffffffffffcc
cbbbbbbbbbbbcccccc1f11f11ccccccccccccccccccccccccccffffffffffffc
cbbbbbbbbbbbccccccf1ff1ffccccccccccccccccccccccccccfffbffffffffc
cbbbbbbbbbbbccccccfffffffccccccccccccccccccccccccccfffbbfffbfffc
cbbbbbbbbbbbccccccccccccccccccccbbbccccbbccccccccccfffffffbbfffc
cbbbbbbbbbbbccccccccccccccccccccbfbcccbffbcccccccccffffffffffffc
cbbbbbbbbbbbccccccccccccccccccccbbbcccbffbcccccccccffffffffffffc
cbbbbbbbbbbbccccccccccccccccccbbbcbbbccbbccccccccccfffbfbbfbfffc
cbbbbbbbbbbbccccccccccccccccccbfbcbfbccffccccccccccffffffffffffc
cbbbbbbbbbbbccccccccccccccccccbbbcbbbcffffcccccccccfffffbbfffffc
cbbbbbbbbbbbcccccceeeeeeeeeeeeeeeeeeeeeeeeeeeccccccffffffffffffc
cbbbbbbbbbbbcccccceeeeeeeeeeeeeeeeeeeeeeeeeeeccccccffffffffffffc
cbbbbbbbbbbbcccccceeceeccccccccccccccccceeceeccccccffffffffffffc
cbbbbbbbbb55cccccceeceeccccccccccccccccceeceeccccccffffffffffffc
cbbbbbbbbb55cccccceeceeccccccccccccccccceeceeccccccffffffffffffc
cbbbbbbfff55cccccceeceeccccccccccccccccceeceeccccccffffffffffffc
cbbbbbbfffcccccccceeceeccccccccccccccccceeceeccccccffffffffffffc
cbbbb55ccccccccccceeccccccccccccccccccccccceeccccccccffffffffffc
c55ff55ccccccccccccccccccccccccccccccccccccccccccccccccffffffffc
c55ffccccccccccccccccccccccccccccccccccccccccccccccccccccffffffc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
`, img`
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccbcccccc3344499ccccccccccccccccccccccccccfcccccccccccc
cccccccccbbbccccccafacfffccccccccccccccccccccccccccfffcccccccccc
cccccccbbbbbccccccfafef5fccccccccccccccccccccccccccfffffcccccccc
cccccbbbbbbbccccccf2fcf1fccccccccccccccccccccccccccfffffffcccccc
cccbbbbbbbbbccccccfafef5fccccccccccccccccccccccccccfffffffffcccc
cbbbbbbbbbbbccccccfafef5fccccccccccccccccccccccccccfffffffffffcc
cbbbbbbbbbbbcccccc1f11f11ccccccccccccccccccccccccccffffffffffffc
cbbbbbbbbbbbccccccf1ff1ffccccccccccccccccccccccccccffffffffffffc
cbbbbbbbbbbbccccccfffffffccccccccccccccccccccccccccffffffffffffc
cbbbbbbbbbbbccccccccccccccccccccbbbccccbbccccccccccffffffffffffc
cbbbbbbbbbbbccccccccccccccccccccbfbcccbffbcccccccccffffffffffffc
cbbbbbbbbbbbccccccccccccccccccccbbbcccbffbcccccccccffffffffffffc
cbbbbbbbbbbbccccccccccccccccccbbbcbbbccbbccccccccccffffffffffffc
cbbbbbbbbbbbccccccccccccccccccbfbcbfbccffccccccccccffffffffffffc
cbbbbbbbbbbbccccccccccccccccccbbbcbbbcffffcccccccccffffffffffffc
cbbbbbbbbbbbcccccceeeeeeeeeeeeeeeeeeeeeeeeeeeccccccffffffffffffc
cbbbbbbbbbbbcccccceeeeeeeeeeeeeeeeeeeeeeeeeeeccccccffffffffffffc
cbbbbbbbbbbbcccccceeceeccccccccccccccccceeceeccccccffffffffffffc
cbbbbbbbbb55cccccceeceeccccccccccccccccceeceeccccccffffffffffffc
cbbbbbbbbb55cccccceeceeccccccccccccccccceeceeccccccffffffffffffc
cbbbbbbfff55cccccceeceeccccccccccccccccceeceeccccccffffffffffffc
cbbbbbbfffcccccccceeceeccccccccccccccccceeceeccccccffffffffffffc
cbbbb55ccccccccccceeccccccccccccccccccccccceeccccccccffffffffffc
c55ff55ccccccccccccccccccccccccccccccccccccccccccccccccffffffffc
c55ffccccccccccccccccccccccccccccccccccccccccccccccccccccffffffc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
`, img`
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccbcccccc3344499ccccccccccccccccccccccccccfcccccccccccc
cccccccccbbbccccccafacfffccccccccccccccccccccccccccfffcccccccccc
cccccccbbbbbccccccfafef5fccccccccccccccccccccccccccfffffcccccccc
cccccbbbbbbbccccccf2fcf1fccccccccccccccccccccccccccfffffffcccccc
cccbbbbbbbbbccccccfafef5fccccccccccccccccccccccccccfffffffffcccc
cbbbbbbbbbbbccccccfafef5fccccccccccccccccccccccccccfffffffffffcc
cbbbbbbbbbbbcccccc1f11f11ccccccccccccccccccccccccccffffffffffffc
cbbbbbbbbbbbccccccf1ff1ffccccccccccccccccccccccccccfffbffffffffc
cbbbbbbbbbbbccccccfffffffccccccccccccccccccccccccccfffbbfffbfffc
cbbbbbbbbbbbccccccccccccccccccccbbbccccbbccccccccccfffffffbbfffc
cbbbbbbbbbbbccccccccccccccccccccbfbcccbffbcccccccccffffffffffffc
cbbbbbbbbbbbccccccccccccccccccccbbbcccbffbcccccccccffffffffffffc
cbbbbbbbbbbbccccccccccccccccccbbbcbbbccbbccccccccccfffbfbbfbfffc
cbbbbbbbbbbbccccccccccccccccccbfbcbfbccffccccccccccffffffffffffc
cbbbbbbbbbbbccccccccccccccccccbbbcbbbcffffcccccccccfffffbbfffffc
cbbbbbbbbbbbcccccceeeeeeeeeeeeeeeeeeeeeeeeeeeccccccffffffffffffc
cbbbbbbbbbbbcccccceeeeeeeeeeeeeeeeeeeeeeeeeeeccccccffffffffffffc
cbbbbbbbbbbbcccccceeceeccccccccccccccccceeceeccccccffffffffffffc
cbbbbbbbbb55cccccceeceeccccccccccccccccceeceeccccccffffffffffffc
cbbbbbbbbb55cccccceeceeccccccccccccccccceeceeccccccffffffffffffc
cbbbbbbfff55cccccceeceeccccccccccccccccceeceeccccccffffffffffffc
cbbbbbbfffcccccccceeceeccccccccccccccccceeceeccccccffffffffffffc
cbbbb55ccccccccccceeccccccccccccccccccccccceeccccccccffffffffffc
c55ff55ccccccccccccccccccccccccccccccccccccccccccccccccffffffffc
c55ffccccccccccccccccccccccccccccccccccccccccccccccccccccffffffc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
`, img`
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccbcccccc3344499ccccccccccccccccccccccccccfcccccccccccc
cccccccccbbbccccccafacfffccccccccccccccccccccccccccfffcccccccccc
cccccccbbbbbccccccfafef5fccccccccccccccccccccccccccfffffcccccccc
cccccbbbbbbbccccccf2fcf1fccccccccccccccccccccccccccfffffffcccccc
cccbbbbbbbbbccccccfafef5fccccccccccccccccccccccccccfffffffffcccc
cbbbbbbbbbbbccccccfafef5fccccccccccccccccccccccccccfffffffffffcc
cbbbbbbbbbbbcccccc1f11f11ccccccccccccccccccccccccccffffffffffffc
cbbbbbbbbbbbccccccf1ff1ffccccccccccccccccccccccccccfffbffffffffc
cbbbbbbbbbbbccccccfffffffccccccccccccccccccccccccccfffbbfffbfffc
cbbbbbbbbbbbccccccccccccccccccccbbbccccbbccccccccccfffffffbbfffc
cbbbbbbbbbbbccccccccccccccccccccbfbcccbffbcccccccccffffffffffffc
cbbbbbbbbbbbccccccccccccccccccccbbbcccbffbcccccccccffffffffffffc
cbbbbbbbbbbbccccccccccccccccccbbbcbbbccbbccccccccccfffbfbbfbfffc
cbbbbbbbbbbbccccccccccccccccccbfbcbfbccffccccccccccffffffffffffc
cbbbbbbbbbbbccccccccccccccccccbbbcbbbcffffcccccccccfffffbbfffffc
cbbbbbbbbbbbcccccceeeeeeeeeeeeeeeeeeeeeeeeeeeccccccffffffffffffc
cbbbbbbbbbbbcccccceeeeeeeeeeeeeeeeeeeeeeeeeeeccccccffffffffffffc
cbbbbbbbbbbbcccccceeceeccccccccccccccccceeceeccccccffffffffffffc
cbbbbbbbbb55cccccceeceeccccccccccccccccceeceeccccccffffffffffffc
cbbbbbbbbb55cccccceeceeccccccccccccccccceeceeccccccffffffffffffc
cbbbbbbfff55cccccceeceeccccccccccccccccceeceeccccccffffffffffffc
cbbbbbbfffcccccccceeceeccccccccccccccccceeceeccccccffffffffffffc
cbbbb55ccccccccccceeccccccccccccccccccccccceeccccccccffffffffffc
c55ff55ccccccccccccccccccccccccccccccccccccccccccccccccffffffffc
c55ffccccccccccccccccccccccccccccccccccccccccccccccccccccffffffc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
`, img`
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccbcccccc3344499ccccccccccccccccccccccccccfcccccccccccc
cccccccccbbbccccccafacfffccccccccccccccccccccccccccfffcccccccccc
cccccccbbbbbccccccfafef5fccccccccccccccccccccccccccfffffcccccccc
cccccbbbbbbbccccccf2fcf1fccccccccccccccccccccccccccfffffffcccccc
cccbbbbbbbbbccccccfafef5fccccccccccccccccccccccccccfffffffffcccc
cbbbbbbbbbbbccccccfafef5fccccccccccccccccccccccccccfffffffffffcc
cbbbbbbbbbbbcccccc1f11f11ccccccccccccccccccccccccccffffffffffffc
cbbbbbbbbbbbccccccf1ff1ffccccccccccccccccccccccccccfff1ffffffffc
cbbbbbbbbbbbccccccfffffffccccccccccccccccccccccccccfff1bfff1fffc
cbbbbbbbbbbbccccccccccccccccccccbbbccccbbccccccccccfffffffb1fffc
cbbbbbbbbbbbccccccccccccccccccccbfbcccbffbcccccccccffffffffffffc
cbbbbbbbbbbbccccccccccccccccccccbbbcccbffbcccccccccffffffffffffc
cbbbbbbbbbbbccccccccccccccccccbbbcbbbccbbccccccccccfff1f11f1fffc
cbbbbbbbbbbbccccccccccccccccccbfbcbfbccffccccccccccffffffffffffc
cbbbbbbbbbbbccccccccccccccccccbbbcbbbcffffcccccccccfffff11fffffc
cbbbbbbbbbbbcccccceeeeeeeeeeeeeeeeeeeeeeeeeeeccccccffffffffffffc
cbbbbbbbbbbbcccccceeeeeeeeeeeeeeeeeeeeeeeeeeeccccccffffffffffffc
cbbbbbbbbbbbcccccceeceeccccccccccccccccceeceeccccccffffffffffffc
cbbbbbbbbb55cccccceeceeccccccccccccccccceeceeccccccffffffffffffc
cbbbbbbbbb55cccccceeceeccccccccccccccccceeceeccccccffffffffffffc
cbbbbbbfff55cccccceeceeccccccccccccccccceeceeccccccffffffffffffc
cbbbbbbfffcccccccceeceeccccccccccccccccceeceeccccccffffffffffffc
cbbbb55ccccccccccceeccccccccccccccccccccccceeccccccccffffffffffc
c55ff55ccccccccccccccccccccccccccccccccccccccccccccccccffffffffc
c55ffccccccccccccccccccccccccccccccccccccccccccccccccccccffffffc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
`, img`
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccbcccccc3344499ccccccccccccccccccccccccccfcccccccccccc
cccccccccbbbccccccafacfffccccccccccccccccccccccccccfffcccccccccc
cccccccbbbbbccccccfafef5fccccccccccccccccccccccccccfffffcccccccc
cccccbbbbbbbccccccf2fcf1fccccccccccccccccccccccccccfffffffcccccc
cccbbbbbbbbbccccccfafef5fccccccccccccccccccccccccccfffffffffcccc
cbbbbbbbbbbbccccccfafef5fccccccccccccccccccccccccccfffffffffffcc
cbbbbbbbbbbbcccccc1f11f11ccccccccccccccccccccccccccffffffffffffc
cbbbbbbbbbbbccccccf1ff1ffccccccccccccccccccccccccccfff1ffffffffc
cbbbbbbbbbbbccccccfffffffccccccccccccccccccccccccccfff1bfff1fffc
cbbbbbbbbbbbccccccccccccccccccccbbbccccbbccccccccccfffffffb1fffc
cbbbbbbbbbbbccccccccccccccccccccbfbcccbffbcccccccccffffffffffffc
cbbbbbbbbbbbccccccccccccccccccccbbbcccbffbcccccccccffffffffffffc
cbbbbbbbbbbbccccccccccccccccccbbbcbbbccbbccccccccccfff1f11f1fffc
cbbbbbbbbbbbccccccccccccccccccbfbcbfbccffccccccccccffffffffffffc
cbbbbbbbbbbbccccccccccccccccccbbbcbbbcffffcccccccccfffff11fffffc
cbbbbbbbbbbbcccccceeeeeeeeeeeeeeeeeeeeeeeeeeeccccccffffffffffffc
cbbbbbbbbbbbcccccceeeeeeeeeeeeeeeeeeeeeeeeeeeccccccffffffffffffc
cbbbbbbbbbbbcccccceeceeccccccccccccccccceeceeccccccffffffffffffc
cbbbbbbbbb55cccccceeceeccccccccccccccccceeceeccccccffffffffffffc
cbbbbbbbbb55cccccceeceeccccccccccccccccceeceeccccccffffffffffffc
cbbbbbbfff55cccccceeceeccccccccccccccccceeceeccccccffffffffffffc
cbbbbbbfffcccccccceeceeccccccccccccccccceeceeccccccffffffffffffc
cbbbb55ccccccccccceeccccccccccccccccccccccceeccccccccffffffffffc
c55ff55ccccccccccccccccccccccccccccccccccccccccccccccccffffffffc
c55ffccccccccccccccccccccccccccccccccccccccccccccccccccccffffffc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
`, img`
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccbcccccc3344499ccccccccccccccccccccccccccfcccccccccccc
cccccccccbbbccccccafacfffccccccccccccccccccccccccccfffcccccccccc
cccccccbbbbbccccccfafef5fccccccccccccccccccccccccccfffffcccccccc
cccccbbbbbbbccccccf2fcf1fccccccccccccccccccccccccccfffffffcccccc
cccbbbbbbbbbccccccfafef5fccccccccccccccccccccccccccfffffffffcccc
cbbbbbbbbbbbccccccfafef5fccccccccccccccccccccccccccfffffffffffcc
cbbbbbbbbbbbcccccc1f11f11ccccccccccccccccccccccccccffffffffffffc
cbbbbbbbbbbbccccccf1ff1ffccccccccccccccccccccccccccfffbffffffffc
cbbbbbbbbbbbccccccfffffffccccccccccccccccccccccccccfffbbfffbfffc
cbbbbbbbbbbbccccccccccccccccccccbbbccccbbccccccccccfffffffbbfffc
cbbbbbbbbbbbccccccccccccccccccccbfbcccbffbcccccccccffffffffffffc
cbbbbbbbbbbbccccccccccccccccccccbbbcccbffbcccccccccffffffffffffc
cbbbbbbbbbbbccccccccccccccccccbbbcbbbccbbccccccccccfffbfbbfbfffc
cbbbbbbbbbbbccccccccccccccccccbfbcbfbccffccccccccccffffffffffffc
cbbbbbbbbbbbccccccccccccccccccbbbcbbbcffffcccccccccfffffbbfffffc
cbbbbbbbbbbbcccccceeeeeeeeeeeeeeeeeeeeeeeeeeeccccccffffffffffffc
cbbbbbbbbbbbcccccceeeeeeeeeeeeeeeeeeeeeeeeeeeccccccffffffffffffc
cbbbbbbbbbbbcccccceeceeccccccccccccccccceeceeccccccffffffffffffc
cbbbbbbbbb55cccccceeceeccccccccccccccccceeceeccccccffffffffffffc
cbbbbbbbbb55cccccceeceeccccccccccccccccceeceeccccccffffffffffffc
cbbbbbbfff55cccccceeceeccccccccccccccccceeceeccccccffffffffffffc
cbbbbbbfffcccccccceeceeccccccccccccccccceeceeccccccffffffffffffc
cbbbb55ccccccccccceeccccccccccccccccccccccceeccccccccffffffffffc
c55ff55ccccccccccccccccccccccccccccccccccccccccccccccccffffffffc
c55ffccccccccccccccccccccccccccccccccccccccccccccccccccccffffffc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
`];
        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "song1":
            case "Toredore March":return hex`0078000408050403001c0001dc00690000045e01000400000000000000000000050000010000030c0030003800012540004800012505001c000f0a006400f4010a00000400000000000000000000000000000000028a0008000c00012910001400012a14001600012a16001800012918001c0001251c002000012520002400012724002800012528002a0001252c003000012430003800012538003c0001274000480001254c005000012450005400012258005c0001276000640001256400680001256c007000012270007400012078007c0001247c008000012280008400012207001c00020a006400f4016400000400000000000000000000000000000000034e0008000c00012910001400012a14001600012a16001800012918001c0001251c002000012520002400012724002800012528002a0001252c003000012430003800012538003c00012740004800012508001c000e050046006603320000040a002d000000640014000100000200000248000400080001060c00100001051400180001061c00200001052400280001062c00300001053400380001063c00400001054400480001064c00500001055400580001065c0060000105`;
        }
        return null;
    })

}
// Auto-generated code. Do not edit.
